# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'walker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftyJSON', '3.1.4'      # 4.0.0
  pod 'Charts', '3.0.3'          # 3.1.1
  # Pods for walker
  target 'walker-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'walkerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
post_install do |installer|
	installer.pods_project.targets.each do |target|
	  target.build_configurations.each do |config|
	    config.build_settings['SWIFT_VERSION'] = '3.0'
	  end
	end
end